FROM node:16-alpine3.15

ENV WAIT_VERSION 2.7.2

WORKDIR /app

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

COPY package.json package-lock.json tsconfig.json ./

RUN npm i
